services:
  - type: web
    name: react-portfolio
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: "/(.*)"
        destination: "/index.html" 